pimcore:
    security:
        # the encoder factory as defined in services.yml
        encoder_factories:
            AppBundle\Model\DataObject\User: app.security.password_encoder_factory

security:
    providers:
        # we use a custom user provider which loads users from the User class
        # the user provider is defined as service in services.yml
        club55:
            id: app.security.user_provider

        firewalls:
            club55:
                pimcore_admin_pre_auth: ~

                anonymous: ~
                # the provider defined above
                provider: club55_provider
                form_login:
                    login_path: club55_login
                    check_path: club55_login
                logout:
                    path:   club55_logout
                    target: club55_login

                    # optional: to keep logins of other firewalls (like admin)
                    invalidate_session: false
                logout_on_user_change: true

        # ROLE_ADMIN inherits ROLE_USER (is allowed everything a user is allowed)
        role_hierarchy:
            ROLE_ADMIN: [ROLE_USER]